#!/bin/bash

# TechCorp Employee Management System
# DevOps Journey Series: Employee Management
# Purpose: Manage employee and department access
# Author: Samiul A Sumel

echo "=== TechCorp Employee Management System ==="
echo "Report Time: $(date)"
echo "Generated By: $(whoami)"
echo "-------------------------------------------"

echo ""

# Section 1: Employee list
echo "=== Company Employee ==="
echo "Username   UID   Home Directory"
echo "-------------------------------------------"
cat /etc/passwd | grep -E "alice|bob|charlie|devops" | cut -d: -f1,3,6
echo ""

# Section 2: Department Groups
echo "=== Department Groups ==="
echo "Group Name   GID   Members"
echo "-------------------------------------------"
cat /etc/group | grep -E "hr|developers|sales|devops" | cut -d: -f1,4
echo ""

# Section 3: Permission Check
echo "=== Department Access Control ==="
echo "HR Directory:"
ls -ld /company-data/hr/
echo ""

echo "Developers Directory:"
ls -ld /company-data/developers/
echo ""

echo "Sales Directory:"
ls -ld /company-data/sales/
echo ""

# Section 4: Security Status
echo "=== Security Status ==="
echo "Users without passwords:"
sudo awk -F: '($2 == "" ) {print $1}' /etc/shadow
sudo awk -F: '($2 == "" || $2 == "!" || $2 == "!!" || $2 == "*") {print $1}' /etc/shadow
echo ""

echo "=== Report Complete ==="