#!/bin/bash

# TechCorp Daily Health Report Script
# This script generates a daily health report for TechCorp's systems.
# Created by: Samiul A Sumel

echo "=== TechCorp Daily Health Report ==="
echo ""

echo "Report Date: $(date)"
echo ""

echo "Generated By: $(whoami)"
echo ""

echo "=== Server Disk Space ==="
echo "Disk space Report: $(df -h | head -n 5)"
echo ""

echo "=== Server Memory Usage ==="
echo "Memory Usage Report: $(free -h)"
echo ""

echo "=== System Uptime ==="
echo "Uptime Report: $(uptime -p)"
echo "Load average: $(uptime | awk -F'load average:' '{ print $2 }')"
echo ""

echo "=== Report Completed ==="
echo "Thank you for using TechCorp's Daily Health Report Script!"